site_name: LoMRF
nav:
    - Home: index.md
    - Quickstart guide: 0_quick_start.md
    - Syntax: 
      - 1_syntax.md    
      - Knowledge Base: 1_1_knowledge_base.md
      - Evidence: 1_2_evidence.md
    - Inference: 
      - 2_inference.md
      - Probabilistic Inference Examples: 2_1_inference_examples.md
      - Temporal Probabilistic Inference Examples: 2_2_temporal_inference_examples.md
    - Weight Learning: 
      - 3_weight_learning.md
      - Weight Learning Examples: 3_1_weight_learning_examples.md
      - Temporal Weight Learning Examples: 3_2_temporal_weight_learning_examples.md
    - Structure Learning: 
      - 4_structure_learning.md
      - Structure Learning Examples: 4_1_structure_learning_examples.md
      - Supervision Completion: 5_supervision_completion.md
    - CLI Tools: 6_tools.md
    - Build from source: 
      - 7_build_test_lomrf.md
      - Build and link: 7_1_build_and_link_lomrf.md
      - Download example data: 7_2_download_example_data.md
    - Configuration: 8_configuration.md
    - References: 9_references.md

theme: readthedocs













